{% set name = "higher" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/higher-{{ version }}.tar.gz
    sha256: f5b7baa668be5dc59cca9ae06c4ed14c2bd2fe5ca8283f95db660e8732513c1d
  - path: version.txt

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - pytorch

test:
  imports:
    - higher
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/facebookresearch/higher
  summary: A pytorch library allowing users to obtain higher order gradients over losses spanning training loops rather than individual training steps.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
